# SkBee's particle system makes Skript parse the code 90x slower, so this is a workaround (delays only for 1 line, not every line
# where you use the effect)
effect [ParticleAPI] %number% %particle% [using %-itemtype/blockdata/dustoption/dusttransition/vibration%] [at] %location% offset %vector% extra %number% for %players%:
	trigger:
		if expr-3 is set:
			play expr-1 of expr-2 particle using expr-3 at expr-4 offset by expr-5 with extra expr-6 for exprs-7
		else:
			play expr-1 of expr-2 particle at expr-4 offset by expr-5 with extra expr-6 for exprs-7
